CLASS zcl_agr_order_event_handler DEFINITION
  PUBLIC ABSTRACT
  FINAL
  FOR EVENTS OF ZAGR_R_Order01TP
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_agr_order_event_handler IMPLEMENTATION.
ENDCLASS.
